apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-queue
  labels:
    app: tech-challenge-queue
spec:
  template:
    metadata:
      name: tech-challenge-queue
      labels:
        app: tech-challenge-queue
    spec:
      containers:
        - name: tech-challenge-queue-api
          image: 767397892937.dkr.ecr.us-east-1.amazonaws.com/queue-service:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-queue-service
                  key: MONGODB_URI
  replicas: 3
  selector:
    matchLabels:
      app: tech-challenge-queue
