apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-queue-service
spec:
  type: LoadBalancer
  selector:
    app: tech-challenge-queue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30002